namespace :utils do
  desc "Fill database with countries"
  # Taken from: http://www.nationsonline.org/oneworld/countries_of_the_world.htm

  task :countries => :environment do
    countries = [
      "Afghanestan",
      "Al Arabiyah as Suudiyah",
      "Al Bahrayn",
      "Al Imarat al Arabiyah al Muttahidah",
      "Al Jaza'ir",
      "Al Kuwayt",
      "Al Maghrib",
      "Al Urdun",
      "Al Yaman",
      "American Samoa",
      "Andorra",
      "Angola",
      "Anguilla",
      "Antarctica",
      "Antigua and Barbuda",
      "Aomen",
      "Aotearoa",
      "Argentina",
      "Aruba",
      "Aṣ-Ṣaḥrā’ al-Gharbīyah",
      "As-Sudan",
      "Australia",
      "Azarbaycan",
      "Bahamas",
      "Bangladesh",
      "Barbados",
      "Belau",
      "Belgique/Belgie",
      "Belize",
      "Benin",
      "Bermuda",
      "Bharat",
      "Bhutan",
      "Bod",
      "Bolivia",
      "Bosna i Hercegovina",
      "Botswana",
      "Brasil",
      "Bulgaria",
      "Burkina Faso",
      "Burundi",
      "Byelarus",
      "Cabo Verde",
      "Cameroon",
      "Canada",
      "Cayman Islands",
      "Ceska Republika",
      "Chile",
      "Choson",
      "Christmas Island",
      "Cocos (Keeling) Islands",
      "Colombia",
      "Comores",
      "Cook Islands",
      "Costa Rica",
      "Cote d'Ivoire",
      "Crna Gora",
      "Cuba",
      "Danmark",
      "Dawlat Qatar",
      "Deutschland",
      "Dhivehi Raajje",
      "Djibouti",
      "Dominica",
      "Dominicana, Republica",
      "Ecuador",
      "Eesti Vabariik",
      "Éire",
      "El Salvador",
      "Ellas or Ellada",
      "España",
      "Estados Unidos Mexicanos",
      "Fiji",
      "Filastin",
      "Foroyar",
      "France",
      "Gabon",
      "Ghana",
      "Gibraltar",
      "Great Britain",
      "Grenada",
      "Guadeloupe",
      "Guam",
      "Guatemala",
      "Guine-Bissau",
      "Guinea Ecuatorial",
      "Guinee",
      "Guyana",
      "Guyane",
      "Hagere Ertra",
      "Haiti",
      "Han-guk",
      "Hayastan",
      "Honduras",
      "Hrvatska",
      "Ile de la Réunion",
      "Indonesia",
      "Iran",
      "Iraq",
      "Islas Malvinas",
      "Italia",
      "Ityop'iya",
      "Jamaica",
      "Jamhuri ya Muungano wa Tanzania",
      "Jumhurii Tojikiston",
      "Kalaallit Nunaat",
      "Kampuchea",
      "Kenya",
      "Kibris, Kypros",
      "Kiribati, Kiribas",
      "Kosova",
      "Kyrgyz Respublikasy",
      "Lao",
      "Latvija",
      "Lesotho",
      "Liberia",
      "Libiyah",
      "Liechtenstein",
      "Lietuva",
      "Lubnan",
      "Luxembourg, Letzebuerg",
      "Lyoveldio Island",
      "Madagascar",
      "Magyarorszag",
      "Makedonija",
      "Malawi",
      "Malaysia",
      "Mali",
      "Malta",
      "Marshall Islands",
      "Martinique",
      "Mauritius",
      "Mayotte",
      "Micronesia",
      "Misr",
      "Mocambique",
      "Moldova",
      "Monaco",
      "Mongol Uls",
      "Montserrat",
      "Muritaniyah",
      "Myanma Naingngandaw",
      "Namibia",
      "Nauru",
      "Nederland/Holland",
      "Nederlandse Antillen",
      "Negara Brunei Darussalam",
      "Nepal",
      "Nicaragua",
      "Niger",
      "Nigeria",
      "Nippon",
      "Niue",
      "Norge",
      "Northern Mariana Islands",
      "Nouvelle-Calédonie",
      "Österreich",
      "Pakistan",
      "Panama",
      "Papua Niu Gini",
      "Paraguay",
      "Peru",
      "Pilipinas",
      "Pitcairn Island",
      "Polska",
      "Polynésie Française",
      "Portugal",
      "Prathet Thai",
      "Puerto Rico",
      "Qazaqstan",
      "Republica Oriental del Uruguay",
      "Republique Centrafricaine",
      "République Démocratique du Congo",
      "République du Congo",
      "Republique Togolaise",
      "Romania",
      "Rossiya",
      "Rwanda",
      "Saint Lucia",
      "Sak'art'velo",
      "Saltanat Uman",
      "Samoa",
      "San Marino",
      "Sao Tome e Principe",
      "Schweiz/Suisse/Svizzera",
      "Senegal",
      "Seychelles",
      "Shqiperia",
      "Sierra Leone",
      "Singapore",
      "Slovenija",
      "Slovensko",
      "Solomon Islands",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Srbija",
      "Sri Lanka",
      "Status Civitatis Vaticanæ",
      "Status Civitatis Vaticanæ",
      "Suomen Tasavalta",
      "Suriname",
      "Suriyah",
      "Sverige",
      "Swaziland",
      "T'ai-wan",
      "Tchad",
      "Terres Australes et Antarctiques Françaises",
      "The Gambia",
      "Timor",
      "Timor",
      "Tokelau",
      "Tonga",
      "Trinidad, Tobago",
      "Tunis",
      "Turkiye",
      "Turkmenistan",
      "Turks and Caicos Islands",
      "Tuvalu",
      "Uganda",
      "Ukrayina",
      "United Kingdom",
      "United States",
      "Uzbekiston Respublikasi",
      "Vanuatu",
      "Venezuela",
      "Viet Nam",
      "Virgin Islands",
      "Wallis et Futuna",
      "Xianggang",
      "Yisra'el",
      "Zambia",
      "Zhong Guo",
      "Zimbabwe"
    ]
    global = Location.find_by_title("Global")

    countries.each do |c|
      Location.create!(
        parent: global,
        title: c,
        description: c,
        total_votes_percent: 50,
        agree_votes_percent: 50
      )
    end
  end
end
